extends = ["saga-shared"]

[env]
FEED_NAME = "wsteth-usd"
PRICE_SERVICE_URL = "http://127.0.0.1:8787"

[commands.relay-threshold]
query_string = "SpotPrice(wsteth,usd)"
price_threshold = 0.0025
offset = 0


