[ethereum]
chain_id = 1
rpcs = [
  "https://mainnet.infura.io/v3/${INFURA_API_KEY}",
  "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}",
  "https://eth.drpc.org"
]
reset_interval_secs = 3600
health_timeout_ms = 3000
error_threshold = 1


[sepolia]
chain_id = 11155111
rpcs = [
  "https://sepolia.infura.io/v3/${INFURA_API_KEY}",
  "https://eth-sepolia.alchemyapi.io/v2/${ALCHEMY_API_KEY}",
  "https://sepolia.drpc.org"
]
reset_interval_secs = 3600
health_timeout_ms = 3000
error_threshold = 1

[base]
chain_id = 8453
rpcs = [
  "https://base-mainnet.infura.io/v3/${INFURA_API_KEY}",
  "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
  "https://base.drpc.org"
]
reset_interval_secs = 3600
health_timeout_ms = 3000
error_threshold = 1