extends = ["saga-shared"]

[env]
FEED_NAME = "reth-usd"

[commands.relay-threshold]
query_string = "SpotPrice(reth,usd)"
sleep_time = 18000
check_interval = 900
backup = true
price_threshold = 0.03
offset = 15
