extends = ["saga-shared"]

[env]
FEED_NAME = "statom-usd"

[commands.relay-threshold]
query_string = "SpotPrice(statom,usd)"
sleep_time = 18000
check_interval = 900
backup = true
price_threshold = 0.03
offset = 30
